### ISSUE TITLE
subprocess stdout/stderr jumbled

### ISSUE THREAD

**Issue by tycho** [mmstick/parallel#11]
Unlike GNU parallel, this tool isn't capturing stdout/stderr from the child process, which results in a mishmash of jumbled output. Needs an equivalent of the `--group` and `--ungroup` options from GNU parallel  (default behaviour with GNU parallel is to use `--group`).

**Comment by mmstick** [comment]
I'll look into adding support for grouping after I add support for stdin.

**Comment by mmstick** [comment]
This is a heads up that I currently have it working, and it will be merged as soon as I finish refactoring and documenting my code.

**Comment by mmstick** [comment]
It's finished https://github.com/mmstick/parallel/commit/ac3d3c40b450077172b099a019c1f3cdfa147e47

**Comment by tycho** [comment]
I'm impressed, nice turnaround time on fixing this!
