### ISSUE TITLE
Output isn't idempotent

### ISSUE THREAD

**Issue by temal-** [mmstick/parallel#12]
Hi,

since the readme states you want to "copy" gnu parallel to some extend and I didn't find a TODO list I thought I create an issue for my observation.

When I run gnu parallel on a set of files I get an ordered and idempotent list of files.
Running your version leaves me with a (sort of) random list after every run.

Keep up the good work!

Regards
Malte

**Comment by mmstick** [comment]
This was already reported, and it's finished https://github.com/mmstick/parallel/commit/ac3d3c40b450077172b099a019c1f3cdfa147e47

**Comment by mmstick** [comment]
Additionally, my current todo list is in the source code
