### ISSUE TITLE
Reading from stdin doesn't dispatch to shell

### ISSUE THREAD

**Issue by ChrisJefferson** [mmstick/parallel#14]
```
~/p/r/parallel ❯❯❯ echo 'echo 1; echo 2;' | gnu-parallel
2
~/p/r/parallel ❯❯❯ echo 'echo 1; echo 2;' | target/debug/parallel
1; echo 2;
```

Worse (for me)

```
~/p/r/parallel ❯❯❯ echo '( cd mydir; echo 2; )' | gnu-parallel
2
~/p/r/parallel ❯❯❯ echo '( cd mydir; echo 2; )' | target/debug/parallel
< just hangs forever >
```

This might be an intentional difference from gnu parallel? I like the fact I can put any arbitrarily complex shell command into the stdin, so I can make subshells, change directories, etc.

**Comment by mmstick** [comment]
For some reason, this didn't occur to me. The fix is stupid simple though: make the command a shell. I'll just have to set up some conditional compilation to account for Windows which does not feature Unix shells like `sh`.

**Comment by mmstick** [comment]
This is now possible: https://github.com/mmstick/parallel/commit/cb908eb764a39993485e09ae356a9c08fc468c01
