### ISSUE TITLE
Support '-k' (or other method of outputting processes as they finish)

### ISSUE THREAD

**Issue by ChrisJefferson** [mmstick/parallel#15]
At the moment mmstick-parallel has two method of outputting:

1) Default: Output jobs in original order.
2) --ungroup: Just dump output as it arrives.

It would be nice to have an inbetween option -- output only complete jobs, but in whatever order they finish. This is the default of gnu-parallel, and the mmstick-parallel default is '-k'. I actually don't mind the default changing, but it's nice to have a way to see jobs as they finish, in case some job hangs, meaning I never see the rest of the finished jobs.

**Comment by mmstick** [comment]
I'll look into how I can do this. I'll probably switch my current method to using this: https://doc.rust-lang.org/std/process/struct.Child.html

**Comment by mmstick** [comment]
I will be submitting a patch and bumping the version with this support soon. It took me a while to figure out how to achieve it, but I have processes printing in order on-demand while they are executing, instead of waiting for them to complete.

**Comment by mmstick** [comment]
It's implemented now: https://github.com/mmstick/parallel/commit/7de6ea4db3789d2cbd81cde8b094df073635cce7
