### ISSUE TITLE
Certain non-text output from launched commands hangs parallel

### ISSUE THREAD

**Issue by Shnatsel** [mmstick/parallel#20]
The following command works with GNU parallel but hangs Rust parallel:

`echo testcase.gz | parallel cat '{}' > /dev/null`

The testcase file is attached: [testcase.gz](https://github.com/mmstick/parallel/files/491407/testcase.gz)

**Comment by mmstick** [comment]
I'll have the test case added as a unit test and I'll try to see what's causing the hang.

**Comment by mmstick** [comment]
I know what's causing it. I'm handling outputs by line-buffering them, but because the binary file does not contain newlines, it is hung waiting to read a newline that will never appear.

**Comment by mmstick** [comment]
I'll have a fix released later today. I submitted a pull request for redox's ion shell to support brace expansion and variable brace expansion yesterday, so today I'm working on getting this fixed.

**Comment by mmstick** [comment]
The 0.5.1 update that I've just merged should fix this problem.
