### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by nkh** [mmstick/parallel#28]
How does one enable support for the '?' operator used since 783a...

rustc --version: rustc 1.12.1 (d4f39402a 2016-10-19)

error: the `?` operator is not stable (see issue #31436)
   --> src/tokenizer/mod.rs:158:44
    |
158 |                             let argument = Number::new(number, token).into_argument(path)?;
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 52 previous errors

error: Could not compile `parallel`.

**Comment by mmstick** [comment]
It was made stable with Rust 1.13
