### ISSUE TITLE
Print ETA to stderr

### ISSUE THREAD

**Issue by Yamakaky** [mmstick/parallel#34]

**Comment by mmstick** [comment]
Is there a use case for this? GNU Parallel seems to print it to stdout too.

**Comment by mmstick** [comment]
https://github.com/mmstick/parallel/commit/68b0af135556ec681a9414229ba7269401220efc

**Comment by Yamakaky** [comment]
You may want to discard the output of the commands but see the ETA.

**Comment by mmstick** [comment]
You can discard command outputs via the `--quiet`/`--silent` flags.
