### ISSUE TITLE
Feature request: Command queue via file

### ISSUE THREAD

**Issue by galiagante** [mmstick/parallel#36]
Sample use case:

A file containing nuanced/complex commands (e.g.):
# cat commands.list
echo "one" && du -hcs ./one
echo "two" && du -hcs ./two
echo "three" && du -hcs ./three

To be executed in parallel like so:
# parallel < commands.list

This would reproduce a useful command-line behavior similar to what's found in recent version of GNU Parallel.

As a work-around, perhaps there's a way to do this in the current version using an alternate syntax?

**Comment by mmstick** [comment]
It works if you enter `target/debug/parallel ::: < inputs` but I can look into it.

**Comment by mmstick** [comment]
This is a mental note on the topic:

I think only a limited number of operating systems that could use this feature (Linux + BSD). I see that it is possible to determine the owner of stdin on *nix systems that feature a `proc` filesystem by using the `readlink` function on `/proc/self/fd/0`. If the link points to `/dev/pts` then there probably isn't any redirection, but if it points to something else then there is input redirection. IE:

```sh
$ readlink /proc/self/fd/0
/dev/pts/4
$ readlink /proc/self/fd/0 < inputs
/home/mmstick/Sources/parallel/inputs
```

**Comment by mmstick** [comment]
This feature has now been implemented. There's three ways to do this now:

```sh
parallel :::: inputs.list
parallel < inputs.list
parallel ::: < inputs.list
```

https://github.com/mmstick/parallel/commit/e72344268ba46cc26610d1a548ef14863df38ef3

**Comment by mmstick** [comment]
Relevant source code for detecting input redirection in Rust:


```rust
pub fn input_was_redirected() -> Option<PathBuf> {
    if let Ok(link) = fs::read_link("/proc/self/fd/0") {
        if !link.to_string_lossy().starts_with("/dev/pts") {
            return Some(link)
        }
    }
    None
}
```
