### ISSUE TITLE
GNU parallel's --no-notice

### ISSUE THREAD

**Issue by Flat** [mmstick/parallel#39]
Some build scripts [1] use parallel with --no-notice [2], which disables the citation printed out to STDERR. parallel (rust) does not include any such citation; it does however exit on receiving a bad flag, this aborts the script even though parallel (rust) can continue fine while ignoring this flag.

I suggest that parallel (rust) silently ignore this flag to be compatible with GNU parallel's usage in scripts such as this.

1. https://github.com/adapta-project/adapta-gtk-theme/blob/1048a2873b9a9b8fe816ffe50391689da3a0c012/gtk/Makefile.am#L892
2. https://lists.gnu.org/archive/html/parallel/2013-11/msg00006.html

**Comment by mmstick** [comment]
Alright then, I'll do this immediately.

**Comment by mmstick** [comment]
https://github.com/mmstick/parallel/commit/f7222003521e366d8a99dc3252c8574fd8c04b2e

**Comment by Flat** [comment]
That was fast, thanks!
