### ISSUE TITLE
-j0: zero cores

### ISSUE THREAD

**Issue by Flat** [mmstick/parallel#40]
It looks like -j0 using MIT/Rust Parallel literally means use 0 cores [1], while -j0 in GNU Parallel means use as many cores/jobs as possible [2]. This makes scripts that use -j0 stall indefinitely upon calling MIT/Rust parallel with the -j0 flag

1. https://github.com/mmstick/parallel/blob/17fe2681c7be0990000ef0e605e2b57ae5e38fba/src/arguments/jobs.rs#L15
2. https://www.gnu.org/software/parallel/man.html

**Comment by mmstick** [comment]
Seems silly to write -j0 when it basically means `choose the default setting`. Nonetheless, I'll fix this shortly.

**Comment by Flat** [comment]
I agree, unfortunately to be compatible as a replacement for GNU Parallel this seems to be used.

**Comment by mmstick** [comment]
[This](https://github.com/mmstick/parallel/commit/51eaf671b8336ee7966c72c894de84b374a59df8) should fix the problem.
