### ISSUE TITLE
Input token {N.} doesn't remove extension

### ISSUE THREAD

**Issue by SuperFluffy** [mmstick/parallel#42]
Giving `parallel` a spin and trying out the example commands. I believe that the input token `{N.}` doesn't do what it's supposed to do:

```bash
% parallel echo {} {1} {2} {3.} ::: 1 2 file.mkv
1 1 2 . 3
2 1 2 . 3
file.mkv 1 2 . 3
```

If I read the description correctly, instead of seeing `. 3` I should see `file`?

```bash
% parallel --version
MIT/Rust Parallel 0.10.7
```

**Comment by mmstick** [comment]
The issue is that your shell is interpreting it. That's what is wrong. Try doing this instead:

```
$ parallel echo '{} {1} {2} {3.}' ::: 1 2 file.mkv
1 1 2 file
2 1 2 file
file.mkv 1 2 file
```

This will prevent your shell from interpreting the braces. You can see how your shell is interpreting commands if you try this (running from fish):

```
$ echo {} {1} {2} {3.}
1 2 3.
```

**Comment by SuperFluffy** [comment]
Yes, you are right indeed! I am using `zsh` and `setopt braceccl` causes `{.3}` to be expanded to a lexically ordered list of characters, in this case `. 3`, as seen above.

Quoting everything works, as does:

```zsh
% unsetopt braceccl; parallel echo '{} {1} {2} {3.}' ::: 1 2 file.mkv 
1 1 2 file
2 1 2 file
file.mkv 1 2 file
```
