### ISSUE TITLE
Change in behaviour of --max-args

### ISSUE THREAD

**Issue by jonasbb** [mmstick/parallel#44]
In version 0.10 the upper first is seen, in version 0.11 the second one. I find the first one more useful and intuitive. From a quick look here, I could not find out why this was changed.

The old behaviour parses multiple args as individual arguments passed to the program, while the new behaviour passes it as a single long space-separated argument.
```
[0] bushart@Colossus07 ~/home $ parallel -n5 'cat {}' ::: 1 2 3 4 5
cat: 1: No such file or directory
cat: 2: No such file or directory
cat: 3: No such file or directory
cat: 4: No such file or directory
cat: 5: No such file or directory

[0] bushart@Colossus07 ~/home $ parallel -n5 'cat {}' ::: 1 2 3 4 5
cat: 1 2 3 4 5: No such file or directory
```

**Comment by mmstick** [comment]
It shouldn't have changed, so I'll fix this later.

**Comment by mmstick** [comment]
Latest change fixes this issue
