### ISSUE TITLE
Mimic GNU Parallel's behavior regarding failing jobs

### ISSUE THREAD

**Issue by justinas** [mmstick/parallel#45]
From my testing, parallel does not have the same behavior as GNU Parallel when some of the jobs fail:

```
justinas@js:~$ /usr/bin/parallel false ::: a b c; echo $?
3
justinas@js:~$ ~/bin/parallel false ::: a b c; echo $?
0
```

That is, GNU Parallel will return a non-zero status code indicating how many jobs have failed, while mmstick/parallel will return 0 even if some jobs fail. Returning a proper status code on failure would be a useful addition for scripting scenarios.

This behavior is documented in GNU Parallel's man page:
```
EXIT STATUS
       If --halt-on-error 0 or not specified:

       0     All jobs ran without error.

       1-253 Some of the jobs failed. The exit status gives the number of failed jobs

       254   More than 253 jobs failed.

       255   Other error.

       If --halt-on-error 1 or 2: Exit status of the failing job.
```

**Comment by mmstick** [comment]
This will be done eventually. I'm working on the [Ion shell](https://github.com/redox-os/ion) at the moment though, and at some point I will attempt to merge the Ion shell as a library into this project to eliminate the need for an external shell, improve performance drastically, and for handling things like this better.

**Comment by mmstick** [comment]
I've implemented this with commit https://github.com/mmstick/parallel/commit/cc2fc355334657a50c0d77e3e48a5f093dde6fc8

**Comment by justinas** [comment]
Amazing, thanks for doing this. :raised_hands:
