### ISSUE TITLE
error return values too high

### ISSUE THREAD

**Issue by ChrisJefferson** [mmstick/parallel#49]
It's a good idea to not return values bigger than 127, see for example https://docs.python.org/3/library/sys.html#sys.exit .

**Comment by mmstick** [comment]
This would break compatibility with GNU Parallel, as per GNU Parallel's manual:

```
EXIT STATUS
       If --halt-on-error 0 or not specified:

       0     All jobs ran without error.

       1-253 Some of the jobs failed. The exit status gives the number of failed jobs

       254   More than 253 jobs failed.

       255   Other error.

       If --halt-on-error 1 or 2: Exit status of the failing job.
```

**Comment by ChrisJefferson** [comment]
Wow, OK. Stupid behaviour from gnu parallel, but it's obviously not caused too many problems. All I personally care about is non-zero, so I'll just ignore this. bash will give programs a return value > 128 if they are killed by a signal, so you lose the ability to track this.
