### ISSUE TITLE
disable the notice of "parallel: reading inputs from standard input"

### ISSUE THREAD

**Issue by wavefancy** [mmstick/parallel#68]
Hi developers,

Can I disable the notice of "parallel: reading inputs from standard input" when reading inputs from the pipe. 

This notice makes rust_paralelel different with gun parallel, and it's not compatible with the Linux philosophy of do not do something extra more. 

Version: MIT/Rust Parallel 0.11.0

Best regards,
Wallace

**Comment by mmstick** [comment]
I'm the only developer, and the project is currently not maintained. In the future, I may rewrite parallel to be up to modern Rusty standards with superior performance, but at the moment I don't have the time.

**Comment by wavefancy** [comment]
Thanks much! Then you can close this for now. Can you please point me where I can edit the source, and compile by myself?

Wallace

**Comment by mmstick** [comment]
The message is [here](https://github.com/mmstick/parallel/blob/master/src/arguments/mod.rs#L369)

**Comment by wavefancy** [comment]
This works perfectly for me!

Wallace

**Comment by ChrisJefferson** [comment]
I just wanted to say, while I can imagine a bit rewrite would be lovely, I'm finding this software is already great for day-to-day use, and it would be nice for it to keep being updated, just to keep it working as well as present. Thanks for the code.
