### ISSUE TITLE
Github releases / binary builds

### ISSUE THREAD

**Issue by ValentinFunk** [mmstick/parallel#69]
I really like this project and was wondering if you are planning to set up a build/ci server (many services are free for open source) to create github releases with compiled binaries for different systems? Right now the installation seems quite complex (especially for people not familiar with rust) and having binary builds available would make it much easier to use the tool for example in Docker Containers.

**Comment by mmstick** [comment]
@Kamshak Development on this has long been paused, until it's eventually rewritten with a better architecture.

**Comment by ValentinFunk** [comment]
Ok, thanks for the update!
