### ISSUE TITLE
cannot be built with rust 1.11

### ISSUE THREAD

**Issue by hroptatyr** [mmstick/parallel#7]
Compiling parallel v0.0.1 (https://github.com/mmstick/parallel#ad8242d3)
    <std macros>:2:21: 2:52 error: expected token: `,`
    <std macros>:2 $ dst . write_fmt ( format_args ! ( $ ( $ arg ) * ) ) )
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/freundt/.cargo/git/checkouts/parallel-0c6613aa1b32f1b5/master/src/main.rs:41:25: 41:94 note: in         this expansion of write! (defined in <std macros>)
    error: aborting due to previous error
    error: failed to compile `parallel v0.0.1 (https://github.com/mmstick/parallel#ad8242d3)`, intermediate     artifacts can be found at `/tmp/cargo-install.3ye1sxZy0nYq`

    Caused by:
      Could not compile `parallel`.

**Comment by mmstick** [comment]
Oops, I don't know how I let that through.

**Comment by mmstick** [comment]
Fixed
