### ISSUE TITLE
Bug: {.} does not properly remove the extension when the basename of a file is one byte

### ISSUE THREAD

**Issue by gnuvince** [mmstick/parallel#76]
Here is an example:

```
$ ls a*.txt
aaa.txt  aa.txt  a.txt

$ parallel echo {.} ::: a*.txt
aaa
aa
a.txt
```

I would expect the last line of the output to be `a`, not `a.txt`.

When the filename use more than one byte, then the replacement works fine:

```
$ ls
a.txt  チ.txt  Σ.txt

$ parallel echo {.} ::: *.txt
a.txt
チ
Σ
```

**Comment by mmstick** [comment]
I'm going to lock this repository because future development will occur in the Redox OS organization with a rewrite from scratch around the Ion shell as a library: https://gitlab.redox-os.org/redox-os/parallel
