### ISSUE TITLE
consider making release (0.1?)

### ISSUE THREAD

**Issue by pvtmert** [mmstick/parallel#8]
so i can add this to homebrew

speed is like 2-3 times faster than gnu-parallel on osx 10.11 el capitan

**Comment by mmstick** [comment]
For the moment you can use this command to install it:

```sh
cargo install --git https://github.com/mmstick/parallel/
```

I will make a release soon, once it is ready.

**Comment by mmstick** [comment]
Release has been made

**Comment by Manouchehri** [comment]
@pvtmert Did you add it to Homebrew? Not seeing it.
